spring:
  main:
    web-application-type: none
    banner-mode: off
  shell:
    history:
      enabled: false
    noninteractive:
      enabled: false
    interactive:
      enabled: false

logging:
  level:
    org:
      springframework: OFF
      hibernate: OFF
    com:
      zaxxer:
        hikari: OFF