spring:
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: ${IMPORT_FILE_MAX_SIZE}
      max-request-size: ${IMPORT_FILE_MAX_SIZE}

springdoc:
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /${SERVER_CONTEXT_PATH}
  port: ${SERVER_PORT}