spring:
  application:
    name: batch-demo
  profiles:
    active: ${APPLICATION_PROFILE}
  messages:
    basename: classpath:i18n/messages
    encoding: UTF-8
    cache-duration: 60
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: ${BATCH_SIZE}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_EXTERNAL_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    aws:
      s3:
        endpoint: ${AWS_S3_ENDPOINT}:${AWS_S3_EXTERNAL_PORT}
        region: ${AWS_S3_REGION}
        bucket: ${AWS_S3_BUCKET_NAME}
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      region:
        static: ${AWS_S3_REGION}

logging:
  level:
    org:
      springframework:
        data: WARN
        batch: WARN
      hibernate: WARN
      jline: OFF
    com:
      zaxxer:
        hikari: WARN