spring:
  config:
    import: optional:file:./dev-tools/.env[.properties]
  docker:
    compose:
      enabled: true
      file: ./dev-tools/docker-compose.yaml
      lifecycle-management: start-and-stop
      start:
        command: up
      stop:
        command: stop